apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  name: bk76ysvpc-go-gitops
  description: This is GitOps manifest for bk76ysvpc-go   
  links:
    - url: https://www.redhat.com/en/solutions/trusted-software-supply-chain
      title: Trusted Secure Supply Chain 
      icon: dashboard
      type: admin-dashboard
  annotations:    
    argocd/app-selector: rhtap/gitops=bk76ysvpc-go
    backstage.io/kubernetes-id: bk76ysvpc-go 
    backstage.io/techdocs-ref: dir:. 
    janus-idp.io/tekton: bk76ysvpc-go   
spec:
  type: gitops
  owner: user:guest 
  lifecycle: experimental
  dependsOn:
    - component:bk76ysvpc-go
