apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: bk76ysvpc-go
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: bk76ysvpc-go 
  name: bk76ysvpc-go
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: bk76ysvpc-go 
